
/***********************************BELOW_SECTION_IS_USED_FOR_TEMPLATE**********************/

var WAIT_FOREVER_TIME=999999999;

//ROW_ALIVE_TYPE_ALIVETIME_RESPONSE_FIRST_COME_FIRST_SERVED will be used as default. User no need to add next button if use this.
var ROW_ALIVE_TYPE_MUST_WAIT_FOR_ALIVE_TIME_REACHED='ROW_ALIVE_TYPE_MUST_WAIT_FOR_ALIVE_TIME_REACHED';//必须等到用户指定的aliveTime才转到下一个row  
var ROW_ALIVE_TYPE_ALIVETIME_RESPONSE_FIRST_COME_FIRST_SERVED='ROW_ALIVE_TYPE_ALIVETIME_RESPONSE_FIRST_COME_FIRST_SERVED';//响应和aliveTime 哪个先到先走原则，如果必须要等待用户响应，则可以设置aliveTime为999999999

//column中的刺激的类型
var STIMULATE_TYPE_NULL='STIMULATE_TYPE_NULL';
var STIMULATE_TYPE_PLAINTEXT='STIMULATE_TYPE_PLAINTEXT';
var STIMULATE_TYPE_BINDANDACCEPTSINGLEKEY='STIMULATE_TYPE_BINDANDACCEPTSINGLEKEY';
var STIMULATE_TYPE_SOUND_SWITCH='STIMULATE_TYPE_SOUND_SWITCH';
var STIMULATE_TYPE_TURNON_SOUND_SWITCH='STIMULATE_TYPE_TURNON_SOUND_SWITCH';
var STIMULATE_TYPE_TURNOFF_SOUND_SWITCH='STIMULATE_TYPE_TURNOFF_SOUND_SWITCH';
var STIMULATE_TYPE_INPUT='STIMULATE_TYPE_INPUT';
var STIMULATE_TYPE_TEXTAREA='STIMULATE_TYPE_TEXTAREA';
var STIMULATE_TYPE_BUTTON='STIMULATE_TYPE_BUTTON';
var STIMULATE_TYPE_RADIOBUTTON='STIMULATE_TYPE_RADIOBUTTON';
var STIMULATE_TYPE_CHECKBOX='STIMULATE_TYPE_CHECKBOX';
var STIMULATE_TYPE_RICHTEXT='STIMULATE_TYPE_RICHTEXT';
var STIMULATE_TYPE_IMAGE='STIMULATE_TYPE_IMAGE';
var STIMULATE_TYPE_SOUND='STIMULATE_TYPE_SOUND';
var STIMULATE_TYPE_FLASH='STIMULATE_TYPE_FLASH';
var STIMULATE_TYPE_VIDEO='STIMULATE_TYPE_VIDEO';
var STIMULATE_TYPE_PRE_CUSTOM_CODE='STIMULATE_TYPE_PRE_CUSTOM_CODE';
var STIMULATE_TYPE_POST_CUSTOM_CODE='STIMULATE_TYPE_POST_CUSTOM_CODE';
var STIMULATE_TYPE_MOUSE_TYPE='STIMULATE_TYPE_MOUSE_TYPE';
var STIMULATE_TYPE_DATE='STIMULATE_TYPE_DATE';

//row的responseType
var RESPONSE_TYPE_SINGLEKEY='RESPONSE_TYPE_SINGLEKEY';
var RESPONSE_TYPE_MULTIPLEKEY='RESPONSE_TYPE_MULTIPLEKEY';
var RESPONSE_TYPE_SINGLEMOUSECLICK='RESPONSE_TYPE_SINGLEMOUSECLICK';
var RESPONSE_TYPE_MULTIPLCLICK='RESPONSE_TYPE_MULTIPLMOUSECLICK';
var RESPONSE_TYPE_RADIOBUTTON='RESPONSE_TYPE_RADIOBUTTON';
var RESPONSE_TYPE_CHECKBOX='RESPONSE_TYPE_CHECKBOX';
var RESPONSE_TYPE_INPUT='RESPONSE_TYPE_INPUT';
var RESPONSE_TYPE_TEXTAREA='RESPONSE_TYPE_TEXTAREA';
var RESPONSE_TYPE_RICHTEXT='RESPONSE_TYPE_RICHTEXT';
var RESPONSE_TYPE_SOUND_SWITCH='RESPONSE_TYPE_SOUND_SWITCH';
var RESPONSE_TYPE_SOUND='RESPONSE_TYPE_SOUND';
var RESPONSE_TYPE_DATE='RESPONSE_TYPE_DATE';


